version: '3'
services:
  xscore-db:
#    container_name: xscore-mysql
#    image: mysql/mysql-server:5.7
    image: mariadb
#    volumes:
#      - ./db/data2:/var/lib/mysql
    environment:
      MYSQL_DATABASE: xscore
      MYSQL_PASSWORD: xscore
      MYSQL_USER: xscore
      MYSQL_ROOT_PASSWORD: xscore
    ports:
      - '3301:3306'
    expose:
      - '3301'
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10


  app:
    restart: always
    image: gradle
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - '13301:8080'
    expose:
      - '13301'
    command: bash -c "sleep 10 && gradle bootRun"
    depends_on:
      - xscore-db
    links:
      - xscore-db