version: '3'
services:
  db:
#    container_name: xscore-mysql
#    image: mysql/mysql-server:5.7
    image: mariadb
#    volumes:
#      - ./db/data2:/var/lib/mysql
    environment:
      MYSQL_DATABASE: xscore
      MYSQL_PASSWORD: xscore
      MYSQL_USER: xscore
      MYSQL_ROOT_PASSWORD: xscore
    ports:
      - '3306:3306'
    expose:
      - '3306'
    restart: always

  app:
    restart: always
    build: ./app
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - '8080:8080'
    expose:
      - '8080'
    command: java -jar /app/build/libs/xscore-0.0.1-SNAPSHOT.jar
    depends_on:
      - db
    links:
      - db