spring:
  application:
    name: xscore
  datasource:
    url: jdbc:mysql://xscore-db:3306/xscore #hostname should be a variable
    driver-class-name: com.mysql.jdbc.Driver
    username: xscore
    password: xscore
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: xscore