FROM openjdk:8-jre

MAINTAINER Roman Velichkin <roman.velichkin@fairprice.com.sg>

ADD ./build/libs/xscore*.jar /app/FP-xscore.jar

CMD ["java", "-Xmx256m", "-jar", "/app/FP-xscore.jar"]

EXPOSE 13301

